// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSDOeed2D-YbkEM1p52S-Al5ChCP_2xOo',
    appId: '1:44746570623:web:af2dde1ef54756d5a2384a',
    messagingSenderId: '44746570623',
    projectId: 'chatapptute-21ba6',
    authDomain: 'chatapptute-21ba6.firebaseapp.com',
    storageBucket: 'chatapptute-21ba6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdoj0yIigocMBi8YGDDaFh5-LGsgknMN8',
    appId: '1:44746570623:android:d5997d39ea21c9d8a2384a',
    messagingSenderId: '44746570623',
    projectId: 'chatapptute-21ba6',
    storageBucket: 'chatapptute-21ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJSVgKQGP3aiCkDuMrYUN1cNWIUpYV8tQ',
    appId: '1:44746570623:ios:3aee836d501275c0a2384a',
    messagingSenderId: '44746570623',
    projectId: 'chatapptute-21ba6',
    storageBucket: 'chatapptute-21ba6.appspot.com',
    iosBundleId: 'com.example.app11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJSVgKQGP3aiCkDuMrYUN1cNWIUpYV8tQ',
    appId: '1:44746570623:ios:3aee836d501275c0a2384a',
    messagingSenderId: '44746570623',
    projectId: 'chatapptute-21ba6',
    storageBucket: 'chatapptute-21ba6.appspot.com',
    iosBundleId: 'com.example.app11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSDOeed2D-YbkEM1p52S-Al5ChCP_2xOo',
    appId: '1:44746570623:web:70ca4bd25bfd6d05a2384a',
    messagingSenderId: '44746570623',
    projectId: 'chatapptute-21ba6',
    authDomain: 'chatapptute-21ba6.firebaseapp.com',
    storageBucket: 'chatapptute-21ba6.appspot.com',
  );
}
